### ISSUE TITLE
By default, the instructions on the webpage require me to `git checkout master`

### ISSUE THREAD

**Issue by Chillee** [fracz/git-exercises#29]
If I do `git clone https://gitexercises.fracz.com/git/exercises.git`, it puts me at commit `030123e4ed762768e8d4a7f0371b1dea583c89e5`, which does not have a `./configure.sh`.

Specifically, this is my output:

```
git clone https://gitexercises.fracz.com/git/exercises.git

Cloning into 'exercises'...
remote: Counting objects: 145, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 145 (delta 29), reused 144 (delta 29)
Receiving objects: 100% (145/145), 33.82 KiB | 4.83 MiB/s, done.
Resolving deltas: 100% (29/29), done.
Note: switching to '030123e4ed762768e8d4a7f0371b1dea583c89e5'.
```

**Comment by remram44** [comment]
The HEAD also points to a commit created by someone else, which contains the solution to the 'ignore-them' exercise. Probably @fracz deleted branches and re-created them, leaving GitHub with the wrong "default branch".

This can be fixed in the settings: https://github.com/fracz/git-exercises/settings/branches

Until this is done, **the "How to start?" instructions on the site do not work**

**Comment by fracz** [comment]
Fixed, thank you
