### ISSUE TITLE
after cloning the repository, configure.sh is missing

### ISSUE THREAD

**Issue by chopeen** [fracz/git-exercises#33]
The repository is cloned in 'detached HEAD' state and there is no `configure.sh` until I manually switch to `master` - is that expected?

```
$ git clone https://gitexercises.fracz.com/git/exercises.git
Cloning into 'exercises'...
remote: Counting objects: 145, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 145 (delta 29), reused 144 (delta 29)
Receiving objects: 100% (145/145), 33.81 KiB | 2.11 MiB/s, done.
Resolving deltas: 100% (29/29), done.
Note: checking out '872524d604359dd8e235bc7f444e601ac88c228d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ cd exercises   

$ ls
file.txt  README.md  start.sh
```

**Comment by BKSpurgeon** [comment]
* I had the same issue -  I could not find the .configure script after cloning. I suspect that the "main" branch for this repository is the "verifications" branch, rather than "master" because it seems to have a lot of work done on it. 
* I could not find the repository for the documentation either: if the OP could kindly point me to it, i could make the relevant change in the documentation to hopefully plug this issue - one could either checkout to the relevant branch as required.

**Comment by fracz** [comment]
Should be fine now.
